 http:
    # 最大连接数
    maxTotal: 200
    # 单个路由最大连接数
    defaultMaxPerRoute: 50
    # 连接上服务器(握手成功)的时间，超出抛出connect timeout
    connectTimeout: 5000
    connectionRequestTimeout: 5000
    # 服务器返回数据(response)的时间，超过抛出read timeout
    socketTimeout: 500
    # 提交前检测是否可用
    staleConnectionCheckEnabled: true
    # 最大空闲时间
    validateAfterInactivity: 5000
spring:
  output:
    ansi:
      enabled: always

#会打印自动配置信息
debug: true