server:
  port: 8083
spring:
  application:
    name: first-eureka-consumer
  logging:
    level:
      com.dragonsoft: debug
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false