-- Oracle
CREATE TABLE T_USER(
  ID VARCHAR2(32) PRIMARY KEY ,
  USERNAME VARCHAR2(32),
  PASSWORD VARCHAR2(32)
);
INSERT INTO T_USER VALUES ('001','zhangsan-oracle','28');
INSERT INTO T_USER VALUES ('002','lisi-oracle','38');
INSERT INTO T_USER VALUES ('003','wangwu-oracle','48');


-- Mysql
CREATE TABLE T_USER(
  ID VARCHAR(32) PRIMARY KEY ,
  USERNAME VARCHAR(32),
  PASSWORD VARCHAR(32)
);
INSERT INTO T_USER VALUES ('001','zhangsan-mysql','28');
INSERT INTO T_USER VALUES ('002','lisi-mysql','38');
INSERT INTO T_USER VALUES ('003','wangwu-mysql','48');