spring:
  messages:
    basename: i18n/login
    encoding: UTF-8
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
    encoding: UTF-8
    content-type: text/html
  mvc:
    date-format: yyyy-MM-dd
server:
  context-path: /crud

#会打印自动配置信息
debug: true