server:
  port: 8082
spring:
  dubbo:
    application:
      name: springboot-dubbo-consumer
    registry:
      address: zookeeper://192.168.18.131
      port: 2181
    protocol:
      name: dubbo
      port: 20890