-- 用户表
CREATE TABLE SYS_USER (
  ID VARCHAR2(32) PRIMARY KEY,
  NAME VARCHAR2(100) NOT NULL,
  PASSWORD VARCHAR2(100) NOT NULL
);
-- 角色表
CREATE TABLE SYS_ROLE (
  ID VARCHAR2(32) PRIMARY KEY,
  NAME VARCHAR2(100) NOT NULL
);
-- 权限角色表(使用USER_ID和ROLE_ID作为联合主键)
CREATE TABLE SYS_USER_ROLE (
  USER_ID VARCHAR2(32),
  ROLE_ID VARCHAR2(32),
  CONSTRAINT PK_SYS_USER_ROLE PRIMARY KEY(USER_ID,ROLE_ID),
  CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE (ID),
  CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES SYS_USER (ID)
);

-- ROLE_XXX，是Spring Security规定权限命名格式
INSERT INTO SYS_ROLE VALUES ('1', 'ROLE_ADMIN');
INSERT INTO SYS_ROLE VALUES ('2', 'ROLE_USER');

INSERT INTO SYS_USER VALUES ('1', 'admin', '123456');
INSERT INTO SYS_USER VALUES ('2', 'user', '123456');

INSERT INTO SYS_USER_ROLE VALUES ('1', '1');
INSERT INTO SYS_USER_ROLE VALUES ('2', '2');