server:
  port: 8080
spring:
  dubbo:
    application:
      name: springboot-dubbo-provide
    registry:
      address: zookeeper://20.20.32.123
      port: 2181
    protocol:
      name: dubbo
      port: 20890
debug: true