server:
  port: 8081
spring:
  profiles:
    active: test
  dubbo:
    application:
      name: springboot-dubbo-provide
    protocol:
      name: dubbo
      port: 20890

---
spring:
  profiles: dev
  dubbo:
    registry:
      address: zookeeper://192.168.18.131
      port: 2181

---
spring:
  profiles: test
  dubbo:
    registry:
      address: zookeeper://20.20.32.123
      port: 2181
