server:
  port: 8080
spring:
  application:
    name: yml
person:
  lastName: zhangsan
  age: 18
  boss: false
  birthday: 2017/12/12
  maps:
    k1: v1
    k2: 12
  lists:
    - lisi
    - zhaoliu
  dog:
    name: xiaogou
    age: 5