server:
  port: 8082
  address: 192.168.18.1
spring:
  application:
    name: first-eureka-provider
eureka:
  instance:
    prefer-ip-address: true
    instance-id: first-eureka-provider-${server.port}
    lease-renewal-interval-in-seconds: 1  #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-expiration-duration-in-seconds: 2 #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
