spring:
  profiles:
    active: produce

---
spring:
  profiles: produce
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtual-host:spring:
---
spring:
  profiles: dev
  rabbitmq:
    host: 192.168.18.131
    username: guest
    password: guest
    port: 5672
    virtual-host: